---
pve:
  hosts:
    pve01:
      ansible_host: pve01.homelab.veselabs.com
      ansible_user: root
    pve02:
      ansible_host: pve02.homelab.veselabs.com
      ansible_user: root
    pve03:
      ansible_host: pve03.homelab.veselabs.com
      ansible_user: root
    pve04:
      ansible_host: pve04.homelab.veselabs.com
      ansible_user: root
    pve05:
      ansible_host: pve05.homelab.veselabs.com
      ansible_user: root
