---
pve:
  hosts:
    pve01:
      ansible_host: pve01.homelab.veselabs.com
      ansible_user: root
      wol_address: E4:B9:7A:F1:98:41
    pve02:
      ansible_host: pve02.homelab.veselabs.com
      ansible_user: root
      wol_address: E4:B9:7A:F5:0A:1C
    pve03:
      ansible_host: pve03.homelab.veselabs.com
      ansible_user: root
      wol_address: E4:B9:7A:F5:07:FB
    pve04:
      ansible_host: pve04.homelab.veselabs.com
      ansible_user: root
      wol_address: E4:B9:7A:F1:9F:79
    pve05:
      ansible_host: pve05.homelab.veselabs.com
      ansible_user: root
      wol_address: E4:B9:7A:F5:13:A7
