pve:
  hosts:
    pve01:
      ansible_host: 10.42.1.11
      ansible_user: root
    pve02:
      ansible_host: 10.42.1.12
      ansible_user: root
    pve03:
      ansible_host: 10.42.1.13
      ansible_user: root
    pve04:
      ansible_host: 10.42.1.14
      ansible_user: root
    pve05:
      ansible_host: 10.42.1.15
      ansible_user: root
