# NOTE: The file extension has to be `yml` to have the proper filetype detected
---
collections:
  - name: community.general
    version: 12.3.0

  - name: community.proxmox
    version: 1.4.0

  - name: artis3n.tailscale
    version: 1.1.0

  - name: prometheus.prometheus
    version: 0.27.6
